package com.example.melon.utils

object Constants {
    const val BASE_URL = "https://socialmedia.bahadorcodes.com/"
    const val CLIENT_TIMEOUT = 600L
    const val DATASTORE_NAME_USER = "user_info"
    const val DATASTORE_TOKEN_USER = "user_key"
    const val DATASTORE_USER_FOLLOWINGS_COLLECTION = "datastore_user_followings_collection"
    const val DATASTORE_USER_FOLLOWERS_COLLECTION = "datastore_user_followers_collection"
    const val DATASTORE_USER_FOLLOWING_REQUESTED_COLLECTION = "datastore_user_following_requested_collection"
    const val DATASTORE_USER_FOLLOWERS_REQUESTED_COLLECTION = "datastore_user_followers_requested_collection"
    var USER_TOKEN = ""
    const val MAIN_ACTIVITY = "main_activity"
    const val FRAGMENT_FIRST = "fragment_first"
    const val FRAGMENT_LOGIN = "fragment_login"
    const val FRAGMENT_SIGNUP = "fragment_signup"
    const val FRAGMENT_HOME = "fragment_home"
    const val FRAGMENT_SEARCH = "fragment_search"
    const val FRAGMENT_ADD_POST = "fragment_add_post"
    const val FRAGMENT_FOLLOWERS = "fragment_followers"
    const val FRAGMENT_FOLLOWINGS = "fragment_followings"
    const val FRAGMENT_NOTIFICATION = "fragment_notification"
    const val FRAGMENT_SHOW_POST = "fragment_show_post"
    const val FRAGMENT_COMMENTS = "fragment_comments"
    const val DO_LIKE_BUTTON = "do_like_button"
    const val GO_TO_COMMENTS_FRAGMENT = "go_to_comments_fragment"
    const val GO_TO_THEIR_USER_PROFILE_FRAGMENT = "go_to_their_user_profile_fragment"
    const val GO_TO_MY_USER_PROFILE_FRAGMENT = "go_to_my_user_profile_fragment"
    const val SEARCH_FRAGMENT_GO_TO_PROFILE_FRAGMENT = "search_fragment_go_to_profile_fragment"
}